import React from "react";
import Head from "next/head";
import DriveHome from "../components/DriveHome";

const Drive = () => {
  return (
    <div>
      <Head>
        <title>Drive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DriveHome />
    </div>
  );
};

export default Drive;
