import Head from "next/head";

import About from "../components/About";
import Footer from "../components/Footer";
import HomePage from "../components/HomePage";
import HowToUse from "../components/HowToUse";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Movie Drive</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="overflow-scroll h-screen overflow-x-hidden">
        <HomePage />
        <About />
        <HowToUse />
        <Footer />
      </div>
    </div>
  );
}
